name: flash_chat
description: Flash Chat Project


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  animated_text_kit: ^4.2.2
  flutter_spinkit: ^5.1.0
  modal_progress_hud_nsn: ^0.2.1

  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  firebase_storage: ^10.2.17
  cloud_firestore: ^3.1.18

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
  - images/
